services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: /bin/sh -c "python manage.py migrate && su appuser -c 'gunicorn --bind 0.0.0.0:8000 cryptoservice.wsgi'"
      - .:/app
      # Убираем volumes для static и media, т.к. они будут обслуживаться Django
    ports:
      - "8000:8000"  # Пробрасываем порт напрямую
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PYTHONPATH=/app:/app/Crypto_Service
      - DJANGO_SETTINGS_MODULE=cryptoservice.settings

volumes:
  postgres_data: