# Generated by Django 4.2 on 2025-05-13 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deposit', models.PositiveIntegerField()),
                ('strategy', models.BooleanField()),
                ('bot_leverage', models.PositiveIntegerField()),
                ('trading_pair', models.CharField(max_length=20)),
                ('take_profit_percent', models.PositiveIntegerField()),
                ('stop_loss_percent', models.PositiveIntegerField()),
                ('grid_orders_count', models.PositiveIntegerField()),
                ('grid_overlap_percent', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('RSI', 'Relative Strength Index'), ('CCI', 'Commodity Channel Index')], max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('parameters', models.JSONField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='bots.bot')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=50)),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField()),
                ('api_secret', encrypted_model_fields.fields.EncryptedCharField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('take_profit_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('stop_loss_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange_commission', models.DecimalField(decimal_places=8, max_digits=20)),
                ('service_commission', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('pnl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('trading_pair', models.CharField(max_length=30)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='bots.bot')),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='exchange_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bots', to='bots.exchangeaccount'),
        ),
        migrations.AddField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
