# Generated by Django 4.2 on 2025-05-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exchangeaccount',
            name='exchange',
            field=models.CharField(choices=[('binance', 'Binance'), ('bybit', 'Bybit'), ('okx', 'OKX')], max_length=50),
        ),
    ]
