# Generated by Django 4.2 on 2025-05-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_deal_order_id_alter_exchangeaccount_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
