# Generated by Django 4.2 on 2025-05-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_bot_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='stop_loss_percent',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
