# Generated by Django 4.2.21 on 2025-06-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_alter_bot_stop_loss_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
