# Generated by Django 4.2.21 on 2025-06-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_alter_deal_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stop_loss_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
    ]
