# Generated by Django 4.2.21 on 2025-06-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_alter_deal_stop_loss_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='stop_loss_percent',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='take_profit_percent',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=5),
        ),
    ]
