# Generated by Django 4.2.21 on 2025-06-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_alter_bot_stop_loss_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
