# Generated by Django 4.2.21 on 2025-06-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_processedtransaction_pendingpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingpayment',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProcessedTransaction',
        ),
        migrations.DeleteModel(
            name='PendingPayment',
        ),
    ]
