# Generated by Django 4.2.21 on 2025-06-28 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bots', '0010_remove_pendingpayment_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=100, unique=True)),
                ('network', models.CharField(choices=[('TRC20', 'TRON (TRC20)'), ('ERC20', 'Ethereum (ERC20)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('timestamp', models.DateTimeField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tx_hash', 'network'], name='bots_crypto_tx_hash_3298b0_idx')],
            },
        ),
    ]
