# Generated by Django 4.2.21 on 2025-07-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_cryptotransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='is_active',
        ),
    ]
