# Generated by Django 4.2.21 on 2025-07-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_cryptotransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='settings_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
