# Generated by Django 4.2.21 on 2025-08-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0015_remove_bot_settings_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='exit_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
    ]
