# Generated by Django 4.2.21 on 2025-06-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_emailconfirmationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='erc20_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trc20_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
